// <auto-generated />
namespace Grupo7_Market.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicionCampoClasificacionProductoTablaProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionCampoClasificacionProductoTablaProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "202111152017246_AdicionCampoClasificacionProductoTablaProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
